# Generated by Django 3.0 on 2019-12-28 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='bk_name')),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y', max_length=10)),
            ],
            managers=[
                ('all_addresses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='bk_name')),
                ('reviews', models.CharField(max_length=10)),
                ('active', models.CharField(default='Y', max_length=10)),
            ],
            managers=[
                ('all_publishers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='bk_name')),
                ('price', models.FloatField()),
                ('cat', models.CharField(max_length=10)),
                ('active', models.CharField(default='Y', max_length=10)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookref', to='bookstore.Publisher')),
            ],
            managers=[
                ('all_books', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='bk_name')),
                ('balance', models.FloatField()),
                ('active', models.CharField(default='Y', max_length=10)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorref', to='bookstore.Address')),
                ('books', models.ManyToManyField(to='bookstore.Book')),
            ],
            managers=[
                ('all_authors', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='publisher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addressref', to='bookstore.Author'),
        ),
    ]
